"""Specialized source field, range, and rename metadata."""

VEHICLE_HBASE_FIELD_OVERRIDES = {
    "l0_mdp.mars_calendar": ["dataid", "m_year", "m_period"],
    "l0_dtr_order.t5_eo_erp_sales_order_line_p": [
        "mars_order_header_no",
        "order_created_at",
        "first_complete_time",
        "order_status",
        "order_source",
        "sold_to_code",
        "sold_to_name",
        "mars_store_code",
        "bmp_eo_order_category",
        "original_amount",
        "pt_sum",
        "coupon_amt",
        "mars_sku_no",
        "bmp_mars_sku_no",
    ],
    "l0_store_center.store_details_p": [
        "mars_region_name",
        "mars_province_name",
        "mars_city_cluster_name",
        "mars_city_name",
        "region_name",
        "region_category",
        "digital_district",
        "code",
        "store_name",
        "channel_name",
        "channel_level2_name",
        "store_channel_name",
        "rtm_channel_name",
        "digital",
        "store_manager_code",
        "store_manager_name",
    ],
    "l2_cot_exe_report.rpt_exe_sales_assess_channel": [
        "salesman_code",
        "salesman_type",
        "sale_role",
        "mars_region_name",
        "mars_province_name",
        "mars_city_cluster_name",
        "mars_city_name",
    ],
    "l1_mdp.vehicle_info_p": [
        "CustomerNo",
        "PlateNo",
        "PersonalNo",
        "SalesmanNo",
        "SalesmanNo2",
        "VehicleStatus",
        "DataType",
        "ModifyDate",
        "CreateDate",
        "PINNo",
    ],
    "l0_customer_center.locust_customer_md": [
        "customer_type_code",
        "mars_geo_region_name",
        "mars_geo_province_name",
        "mars_geo_city_clusters_name",
        "mars_geo_city_name",
        "division",
        "code",
        "name",
    ],
    "l0_product_center.locust_product_md": ["prod_code", "subsegment"],
}

VEHICLE_HBASE_RANGE_OVERRIDES = {
    "l0_mdp.mars_calendar": {"start_time": None, "end_time": None, "row_prefixs": False, "is_row_prefixs": None},
    "l0_dtr_order.t5_eo_erp_sales_order_line_p": {
        "start_time": "P",
        "end_time": "P",
        "row_prefixs": True,
        "is_row_prefixs": "YES",
    },
    "l0_store_center.store_details_p": {
        "start_time": "period",
        "end_time": "period",
        "row_prefixs": False,
        "is_row_prefixs": None,
    },
    "l2_cot_exe_report.rpt_exe_sales_assess_channel": {
        "start_time": "P",
        "end_time": "P",
        "row_prefixs": True,
        "is_row_prefixs": "YES",
    },
    "l1_mdp.vehicle_info_p": {
        "start_time": "period",
        "end_time": "period",
        "row_prefixs": True,
        "is_row_prefixs": "YES",
    },
    "l0_customer_center.locust_customer_md": {
        "start_time": None,
        "end_time": None,
        "row_prefixs": False,
        "is_row_prefixs": None,
    },
    "l0_product_center.locust_product_md": {
        "start_time": None,
        "end_time": None,
        "row_prefixs": False,
        "is_row_prefixs": None,
    },
}

VEHICLE_RENAME_MAP = {
    "l0_customer_center.locust_customer_md": {"code": "customer_code"},
    "l2_cot_exe_report.rpt_exe_sales_assess_channel": {"salesman_code": "store_manager_code"},
    "l1_mdp.vehicle_info_p": {
        "PlateNo": "vehicle_num",
        "VehicleStatus": "vehicle_status",
        "DataType": "vehicle_tool",
        "PersonalNo": "store_manager_code",
        "CustomerNo": "customer_code",
    },
}

VEHICLE_FS_FIELD_OVERRIDES = {
    "dms_order": [
        "mars_store_code",
        "org_mars_order_header_no",
        "org_dtr_created_at",
        "update_time",
        "marsk",
        "reason_for_reversal",
        "qct_total",
        "sales_amount",
        "org_coupon_amt",
        "supplier_code",
        "supplier_name",
        "org_dtr_source_type",
        "category",
    ],
    "dms_md": ["code", "status", "belongs_to_code", "belongs_to_name"],
}

SUPERVISOR_HBASE_CANONICAL_NAMES = {
    "l0_eo.order_detail_sync": "l0_eo.order_details_sync",
    "l2_cot_exe_report.rpt_exe_visit_planning_execute_rate_2025": "l2_cot_exe_report.rpt_exe_visit_planning_execute_rate",
}

SUPERVISOR_HBASE_FIELD_OVERRIDES = {
    "l0_eo.order_details_sync": [
        "customers_code",
        "order_date",
        "order_status",
        "order_pt_sum",
        "product_std_code",
    ],
    "l2_cot_exe_report.rpt_exe_visit_planning_execute_rate": [
        "store_code",
        "today_executed",
        "planning_date",
        "visit_emp_segment",
    ],
    "l0_cot_visit.store_planning": [
        "store_code",
        "planning_date",
        "user_segment",
    ],
    "l0_user_center.user_information": [
        "emp_code",
        "emp_name",
        "level_code",
        "emp_type_name",
        "parent_emp_code",
        "parent_emp_name",
        "ad_account",
        "mars_geo_code1",
        "mars_geo_name1",
        "mars_geo_code2",
        "mars_geo_name2",
        "mars_geo_code3",
        "mars_geo_name3",
        "mars_geo_code4",
        "mars_geo_name4",
        "status",
        "org_code_ hierachy",
        "org_name_ hierachy",
        "roles_code",
        "roles_name",
        "is_cheetah",
        "is_vehicle",
        "is_wholesale",
        "is_lst",
        "user_channel",
        "created",
        "updated",
        "id",
        "segment",
    ],
    "l0_product_center.locust_product_md": ["prod_code", "segment", "subsegment"],
}

SUPERVISOR_HBASE_RANGE_OVERRIDES = {
    "l0_eo.order_details_sync": {"start_time": "p_start", "end_time": "p_end", "row_prefixs": True},
    "l2_cot_exe_report.rpt_exe_visit_planning_execute_rate": {
        "start_time": "period",
        "end_time": "period",
        "row_prefixs": True,
    },
    "l0_cot_visit.store_planning": {"start_time": "currentday", "end_time": "currentday", "row_prefixs": True},
    "l0_user_center.user_information": {"start_time": None, "end_time": None, "row_prefixs": False},
    "l0_product_center.locust_product_md": {"start_time": None, "end_time": None, "row_prefixs": False},
}

SUPERVISOR_MSSQL_FIELD_OVERRIDES = {
    "topic_supervisor_portal.store_details": [
        "mars_region_code",
        "mars_province_code",
        "mars_city_cluster_code",
        "mars_city_code",
        "region_code",
        "chain_brand_code",
        "nation_hq_code",
        "city_hq_code",
        "ka_type_code",
        "channel_code",
        "channel_level2_code",
        "store_channel_code",
        "rtm_channel_code",
        "mars_region_name",
        "mars_province_name",
        "mars_city_cluster_name",
        "mars_city_name",
        "region_name",
        "chain_brand_name",
        "nation_hq_name",
        "ka_type_name",
        "city_hq_name",
        "code",
        "store_name",
        "cover_mode",
        "channel_name",
        "channel_level2_name",
        "store_channel_name",
        "store_level",
        "wal_mart",
        "salesman_code",
        "salesman_name",
        "state",
        "digital",
        "rtm_channel_name",
        "store_kk",
        "store_manager_code",
        "store_manager_name",
        "closed_date",
    ],
    "topic_supervisor_portal.eo_order_detail_pool": [
        "store_code",
        "create_time",
        "order_state",
        "pt_sum",
        "product_code",
    ],
    "topic_supervisor_portal.fts_store_visit_log": ["store_id", "created_timestamp", "status"],
}

SUPERVISOR_MSSQL_RANGE_OVERRIDES = {
    "topic_supervisor_portal.store_details": {"time_col": None},
    "topic_supervisor_portal.eo_order_detail_pool": {
        "time_col": "create_time",
        "start_time": "current_date",
        "end_time": "current_date",
    },
    "topic_supervisor_portal.fts_store_visit_log": {
        "time_col": "created_timestamp",
        "start_time": "p_start_time",
        "end_time": "current_date",
    },
}

SUPERVISOR_MSSQL_RENAME_MAP = {
    "topic_supervisor_portal.store_details": {"code": "store_code"},
    "store_details": {"code": "store_code"},
}

FIXED_PLATFORM_PACKAGE_DIRS = {"gateway", "hbase", "fs"}
